[package]
name = "trine-kv-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
trine-kv = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "manifest"
path = "fuzz_targets/manifest.rs"
test = false
doc = false
bench = false

[[bin]]
name = "wal"
path = "fuzz_targets/wal.rs"
test = false
doc = false
bench = false

[[bin]]
name = "table"
path = "fuzz_targets/table.rs"
test = false
doc = false
bench = false

[[bin]]
name = "blob"
path = "fuzz_targets/blob.rs"
test = false
doc = false
bench = false

[[bin]]
name = "upload"
path = "fuzz_targets/upload.rs"
test = false
doc = false
bench = false

[[bin]]
name = "object_control"
path = "fuzz_targets/object_control.rs"
test = false
doc = false
bench = false
